spring:
  data:
    mongodb:
      username: ahmedyasser
      password: ahmedyasser
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

server:
  port: 8090
